---
#
# Ansible managed
#
repository:
  description: Install and configure zabbix-proxy on your system.
  homepage: https://buluma.github.io/
  topics: zabbix, proxy, ansible, molecule, tox, playbook, hacktoberfest
